### ISSUE TITLE
hello, give me a smaple,thx

### ISSUE THREAD

**Issue by netstu** [mitchdowd/jnipp#16]
how to set a object?

for example:

class a {
      private String aa;
      private int bb;
      public static b bobj;
}

class b {.....}

b bobj = new b();

a native method param is b, how to set class a.b = bobj;

jniexport void java_com_daaa_xx(JNIEVN env*, jobject thiz, jobject bobj)  {

 // in here , how to set class a.b = bobj;

}

**Comment by mitchdowd** [comment]
Hi @netstu 

Firstly, that `Java_com_daa_xx()` function would need to correspond with a native method on class `a`.

So, in your Java...
```
package com.netsu;

class a {
    public native void doStuff(b bobj);
}
```
So then in your C++ code, you can make `doStuff()` call that assignment by using `set()`.
```
extern "C" void Java_com_netsu_a_doStuff(jni::JNIEnv* env, jni::jobject obj, jni::jobject bobj)
{
    jni::init(env);
    jni::Object aobj(obj);  // The aobj is "this" object.
    aobj.set<jni::jobject>(bobj, "b"); // Set variable "b" on aobj to bobj.
}
```

This is the equivalent of:
```
void doStuff(b bobj)
{
    this.b = bobj;
}
```
