### ISSUE TITLE
GetStringUTFChars  convert utf-16 to utf-8 may cause error

### ISSUE THREAD

**Issue by qtfreet00** [mitchdowd/jnipp#27]
GetStringUTFChars cannot support emoji ,such as 👇

**Comment by mitchdowd** [comment]
Hi @qtfreet00, thanks for the info.  I just did some searching.  What `GetStringUTFChars()` actually does is converts to a _modified_ UTF-8 (i.e.  "Not really UTF-8"), if that is what you're referring to.

jnipp is merely a wrapper around the JNI so far, and doesn't attempt to add any extra functionality, such as UTF-8 conversions.  Is your issue that you are after a UTF-8 representation of the test within the returned `std::string`?
